default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin
  password: password
  host: localhost

development:
  <<: *default
  database: atask-payment-api-db

test:
  <<: *default
  database: atask-payment-api-db-test

production:
  <<: *default
  database: atask-payment-api-db-prod
  username: <%= ENV['PAYMENT_API_DATABASE_USERNAME'] %>
  password: <%= ENV['PAYMENT_API_DATABASE_PASSWORD'] %>
